[package]
name = "ft-state"
version = "0.1.4"
edition = "2021"

[dependencies]
gstd = { git = "https://github.com/gear-tech/gear", branch = "testnet" }
gmeta = { git = "https://github.com/gear-tech/gear", branch = "testnet", features = ["codegen"] }
ft-io = { path = "../io" }

[build-dependencies]
gear-wasm-builder = { git = "https://github.com/gear-tech/gear", branch = "testnet", features = ["metawasm"] }
