version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "contracts"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "."
    schedule:
      interval: "daily"
