image: gitpod/workspace-rust
tasks:
  - init: |
      sudo apt update
      sudo apt install cmake binaryen -y
      [ $DAPP ] && gp open contracts/$DAPP/src/lib.rs
      clear
vscode:
  extensions:
    - rust-lang.rust-analyzer
