[workspace]
resolver = "2"

[workspace.package]
homepage = "https://wiki.gear-tech.io/docs/examples/prerequisites"
documentation = "https://dapps.gear.rs"
authors = ["Gear Foundation <hello@gear.foundation>"]
license = "MIT"
edition = "2021"
publish = false

[workspace.dependencies]
