[package]
name = "gear-feeds-router"
version = "0.1.0"
authors = ["Gear Technologies"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.2.1", default-features = false, features = ["derive"] }
gstd = { git = "https://github.com/gear-tech/gear.git", features = ["debug"], branch = "stable" }
router-io = { path = "io" }

[build-dependencies]
gear-wasm-builder = { git = "https://github.com/gear-tech/gear.git" , branch = "stable" }
