name: Contracts CI

on:
  pull_request:
  push:
    branches: [master]
    tags: ['[0-9]+.[0-9]+.[0-9]+']

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    working-directory: contracts

permissions:
  contents: write
  id-token: write
  pages: write

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  all:
    name: All
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: CI
      #   if: github.ref_type != 'tag'
      #   run: cargo xtask ci

      - name: Update the nightly tag
        if: github.ref == 'refs/heads/master'
        run: |
          git tag -f nightly
          git push -f origin nightly

      - name: Build
        if: github.event_name != 'pull_request'
        run: cargo b

      - name: Release
        if: github.event_name != 'pull_request'
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.ref == 'refs/heads/master' && 'Nightly' || github.ref_name }}
          files: |
            contracts/target/wasm32-unknown-unknown/debug/*.*.wasm
            contracts/target/wasm32-unknown-unknown/debug/*.meta.txt

      - name: Generate documentation
        if: github.ref == 'refs/heads/master'
        run: |
          cargo xtask docs

      - name: Upload the GitHub Pages artifact
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-pages-artifact@v2
        with:
          path: contracts/target/doc

      - name: Deploy GitHub Pages
        if: github.ref == 'refs/heads/master'
        uses: actions/deploy-pages@v2
