name: Contracts CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  all:
    name: All
    runs-on: self-hosted
    defaults:
      run:
        working-directory: contracts
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: CI
        run: cargo xtask ci
