name: Contracts CI & Build

on:
  push:
    branches: [master]
    tags:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: contracts
    permissions:
      id-token: write
      contents: write
      pages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build & move the `nightly` tag
        run: |
          cargo xtask docs
          rm target/doc/.lock
          git tag nightly
          git push -f --tags

      - name: Upload the GitHub Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: contracts/target/doc

      - name: Deploy GitHub Pages
        uses: actions/deploy-pages@v2

      - name: Release the nightly build
        uses: softprops/action-gh-release@v1
        with:
          name: Nightly
          tag_name: nightly
          files: contracts/target/doc/help.html

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: contracts/target/doc/help.html
