name: Contracts Build

on:
  push:
    branches: [master]
    tags:

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    uses: ./.github/workflows/contracts-check.yml

  build:
    name: Build
    needs: check
    runs-on: self-hosted
    defaults:
      run:
        working-directory: contracts
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: CI
        run: cargo b
