name: Contracts CI - Tests

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - 'frontend/**'
      - 'docker/**'
  push:
    paths-ignore:
      - 'frontend/**'
      - 'docker/**'
    branches: [master]

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    working-directory: contracts

permissions:
  contents: write
  id-token: write
  pages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  all:
    name: Tests
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python (to get the latest GEAR version)
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Get latest GEAR version
        id: get_gear_version
        run: |
          import re
          import requests

          GEAR_REPO_TAGS_URL = "https://api.github.com/repos/gear-tech/gear/tags"
          
          response = requests.get(GEAR_REPO_TAGS_URL)
          response.raise_for_status()
          tags = response.json()

          # Filter valid semantic versioning tags (vX.Y.Z format)
          valid_tags = [tag['name'] for tag in tags if re.match(r'^v\d+\.\d+\.\d+$', tag['name'])]
          # Sort tags by version in descending order
          valid_tags.sort(key=lambda s: [int(part) for part in s.lstrip('v').split('.')], reverse=True)

          latest_version = valid_tags[0] if valid_tags else None
          if latest_version:
              print(f"::set-output name=GEAR_VERSION::{latest_version.lstrip('v')}")
          else:
              raise Exception("No valid GEAR version found")

      - name: Set up Rust (Stable)
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown

      - name: Prepare Gear Binary
        run: |
          mkdir -p target/tmp
          wget -qO- https://get.gear.rs/gear-v${{ steps.get_gear_version.outputs.GEAR_VERSION }}-x86_64-unknown-linux-gnu.tar.xz | tar xJ -C target/tmp

      # mandatory tasks
      - name: Fmt
        run: 'cargo +nightly fmt --all -- --config imports_granularity=Crate,edition=2021'
      - name: Clippy
        run: 'cargo clippy --release --workspace --all-targets --all-features -- -D warnings'
      - name: Test
        run: cargo test --release --workspace
