name: Update GEAR Dependencies

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch: # Allows manual triggering of the workflow

defaults:
  run:
    working-directory: scripts

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.UPDATE_GEAR_TAG_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests packaging gitpython

    - name: Check for new tag and update Cargo.toml
      env:
        GITHUB_TOKEN: ${{ secrets.UPDATE_GEAR_TAG_TOKEN }}
      run: |
        python update_gear_version.py
        if ! git diff --exit-code; then
          # Configure git
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Output changes for logging
          echo "The following changes were made:"
          git diff

          # Create a new branch
          branch_name="update-gear-dependencies-$(date +%Y%m%d%H%M%S)"
          git checkout -b $branch_name

          # Stage and commit changes
          git add ../contracts/Cargo.toml
          git commit -m "Update GEAR dependencies to latest tag in contracts"

          # Push the new branch
          git push origin $branch_name

          # Install GitHub CLI
          sudo apt-get update && sudo apt-get install gh -y

          # Create a pull request using GitHub CLI
          gh pr create --title "Update GEAR dependencies" --body "Automatically created pull request to update GEAR dependencies" --base master --head $branch_name
        fi
