name: Update GEAR Dependencies

on:
  schedule:
    - cron: '*/30 * * * *' # Runs every 30 minutes
  workflow_dispatch: # Allows manual triggering of the workflow

defaults:
  run:
    working-directory: scripts

permissions:
  contents: write
  actions: write
  pull-requests: write

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.WF_SECRET }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests packaging gitpython

    - name: Remove Cargo.lock file
      run: |
        echo "Removing contracts/Cargo.lock"
        rm -f ../contracts/Cargo.lock

    - name: Check for new tag and update Cargo.toml
      env:
        GITHUB_TOKEN: ${{ secrets.WF_SECRET }}
      run: |
        python update_gear_version.py
        if ! git diff --exit-code; then
          echo "Changes detected in the repository after running the update_gear_version.py script."

          # Configure git
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Output changes for logging
          echo "The following changes were made:"
          git diff

          # Create a new branch
          branch_name="update-gear-dependencies-$(date +%Y%m%d%H%M%S)"
          echo "Creating a new branch: $branch_name"
          git checkout -b $branch_name

          # Stage and commit changes
          echo "Staging changed files."
          git add ../contracts/Cargo.toml
          git add ../.github/workflows/contracts-tests.yml
          git add ../contracts/Cargo.lock

          echo "Committing changes with message: 'Update GEAR dependencies to latest tag in contracts'"
          git commit -m "Update GEAR dependencies to latest tag in contracts"

          # Push the new branch
          echo "Pushing the new branch: $branch_name"
          git push origin $branch_name

          # List open PRs with a specific label
          open_prs=$(gh pr list --label "auto-update-gear" --state open --json number --jq '.[].number')

          for pr in $open_prs; do
            # Get PR details locally
            pr_branch=$(gh pr view $pr --json headRefName --jq '.headRefName')
            git fetch origin $pr_branch

            # Compare local changes
            pr_diff=$(git diff origin/$pr_branch)
            current_diff=$(git diff HEAD~1 HEAD)

            if [ "$pr_diff" = "$current_diff" ]; then
              echo "An open pull request with the same changes already exists: #$pr"
              exit 0
            fi
          done

          # If no matching PR was found, create a new PR with a specific label
          echo "No matching open PR found, creating a new pull request."
          gh pr create --title "Update GEAR dependencies" --body "Automatically created pull request to update GEAR dependencies" --base master --head $branch_name --label "auto-update-gear"
        else
          echo "No changes were detected after running the update_gear_version.py script."
        fi
